# Generated by Django 4.1 on 2023-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mission_point',
            field=models.IntegerField(default=0),
        ),
    ]
