# Generated by Django 4.1 on 2023-07-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_customuser_mission_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
