# Generated by Django 4.1 on 2023-07-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0005_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
