# Generated by Django 4.1 on 2023-05-02 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField(max_length=5, verbose_name='ランク')),
                ('mission', models.TextField(max_length=100, verbose_name='ミッション')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
            ],
        ),
        migrations.CreateModel(
            name='MissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_time', models.DateTimeField(verbose_name='抽選日時')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.mission', verbose_name='ミッション')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Gather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('access', models.CharField(max_length=200, verbose_name='アクセス')),
                ('contact', models.CharField(max_length=254, verbose_name='連絡先')),
                ('detail', models.TextField(max_length=300, verbose_name='詳細')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.prefecture', verbose_name='都道府県')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='募集主')),
            ],
        ),
    ]
