# Generated by Django 4.1 on 2023-06-05 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0007_communitygenre_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='メッセージ')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('best_flg', models.BooleanField(default=False, verbose_name='ベストアンサー')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='best_answer',
            field=models.BooleanField(default=False, verbose_name='ベストアンサー'),
        ),
        migrations.AddField(
            model_name='community',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seed.communitygenre', verbose_name='Community ジャンル'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.communitymessage', verbose_name='CommunityMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.community', verbose_name='Community'),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
