# Generated by Django 4.1 on 2023-06-12 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_communitymessage_community_best_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='賞味・消費期限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='expiration',
            field=models.BooleanField(default=False, verbose_name='消費期限'),
            preserve_default=False,
        ),
    ]
