# Generated by Django 4.1 on 2023-07-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0009_product_deadline_product_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.IntegerField(default=268, verbose_name='定価'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='割引価格'),
        ),
    ]
