# Generated by Django 4.1 on 2023-05-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(upload_to='images/', verbose_name='商品画像')),
                ('detail', models.TextField(max_length=300, verbose_name='詳細')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='掲載企業')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.genre', verbose_name='ジャンル')),
            ],
        ),
    ]
