# Generated by Django 4.1 on 2023-05-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gather',
            name='image',
            field=models.ImageField(null=True, upload_to='gather_img/', verbose_name='画像'),
        ),
    ]
